name: test the release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    needs: build-artifacts
    steps:
      - uses: actions/checkout@v3
      - name: Remove potentially lingering release
        uses: unkies/delete-tag-and-release@main
        with:
          delete_release: true
          tag_name: test-release
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Create Test Release
        uses: softprops/action-gh-release@v1
        with:
          name: Test release
          tag_name: test-release
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Clean up release
        uses: unkies/delete-tag-and-release@main
        with:
          delete_release: true
          tag_name: test-release
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
